bankingapp/urls.py
from django.conf.urls import url
from bankingapp import views
#from bankingapp.views import HomeView


# name spacing for the bankingapp
app_name = 'bankingapp'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^apphome/$', views.apphome, name='apphome'),
    url(r'^utilitybillstransactions/$', views.utilitybillstransactions, name='utilitybillstransactions'),
    url(r'^fundstransactions/$', views.fundstransactions, name='fundstransactions'),
    url(r'^monthlystatements/$', views.monthlystatements, name='monthlystatements'),
    url(r'^fundstransfer/$', views.fundstransfer, name='fundstransfer'),
    url(r'^payutilities/$', views.payutilities, name='payutilities'),
    url(r'^updateprofile/$', views.updateprofile, name='updateprofile'),
    url(r'^accesslogs/$', views.accesslogs, name='accesslogs'),
    url(r'^signup/$', views.signup, name='signup'),

]

onlinebanking/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from bankingapp import views
from django.conf import settings
from django.conf.urls.static import static
from registration.backends.simple.views import RegistrationView

# Create a new class that redirects the user to the homepage,
# if successful at logging

class BankingRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return '/bankingapp/'



urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^accounts/register/$', BankingRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),

    url(r'^bankingapp/', include('bankingapp.urls')),
    url(r'^admin/', admin.site.urls),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bankingapp/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

class UserProfile(User):
    idNumber = models.CharField(max_length=30, verbose_name="Customer ID number", blank=True)
    city = models.CharField(max_length=20,verbose_name="Customer City", null=True, default=None)
    lastAccess = models.DateTimeField(auto_now=True, verbose_name="Time of last successful login")
    slug = models.SlugField(unique=True)

    # Create automatically the slugfield entry
    def save(self, *args, **kwargs):
        self.slug = slugify(self.first_name)
        super(UserProfile, self).save(*args, **kwargs)

    def __str__(self):
        return self.first_name

class UserBankAccount(models.Model):
    ACCOUNT_CHOICES = (
    ('current', 'Current Account'),
    ('savings', 'Savings Account'),
    )
    accountID = models.OneToOneField(UserProfile, on_delete=models.CASCADE, primary_key=True, related_name="account_number")
    accountNumber = models.CharField(max_length=10, verbose_name="Customer Account Number", default=None)
    bankName = models.CharField(max_length=50, verbose_name="Customer Bank Name", default=None)
    accountType = models.CharField(max_length=10, verbose_name="Customer Account Type", choices=ACCOUNT_CHOICES,default='current')
    accountBalance = models.IntegerField(verbose_name=" Customer Current Account Balance", default=0)
    createdAt = models.DateField(verbose_name="Date of Account Creation", auto_now_add=True)
    bankBranch = models.CharField(max_length=50, verbose_name="Name of Account Branch", default=None)

    class Meta:
        ordering = ('-createdAt',)

    def __str__(self):
        return self.accountNumber


class UtilityCompany(models.Model):
    companyName = models.CharField(max_length=50, verbose_name=" Company Name", default=None)
    companyAccountNum = models.CharField(max_length=10,verbose_name="Company Account Number", default=None)
    companyAccountBalance = models.IntegerField(verbose_name=" Company Account Balance", default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.companyName)
        super(UtilityCompany, self).save(*args, **kwargs)

    def __str__(self):
        return self.companyName


class UtilityPayment(models.Model):
    UTILITY_CHOICES = (
    ('Water Bill','Monthly Water Bill'),
    ('Gas Bill', 'Monthly Gas Bill'),
    ('Power Bill', 'Monthly Power Bill')
    )
    billID = models.ForeignKey(UtilityCompany, on_delete=models.CASCADE, related_name='bill_ID')
    billName = models.CharField(max_length=30, verbose_name="Utility Bill Name", choices=UTILITY_CHOICES, default='Water Bill')
    billAmount = models.IntegerField(default=0, verbose_name="Bill Amount")
    customerName = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    paymentDate = models.DateField(verbose_name="Date of Payment", auto_now=True)
    billDescription = models.CharField(verbose_name="Description of Bill to be Paid", max_length=100, default=None)

    def __str__(self):
        return self.billName

class FundsTransfer(models.Model):
    TRANSFER_CHOICES = (
    ('Funds Transfer', 'Funds Transfer'),
    )
    transferID = models.ForeignKey(UserProfile, on_delete=models.CASCADE, verbose_name="Money Sender")
    transferAmount = models.IntegerField(verbose_name="Amount to transfer", default=0)
    transferAccount = models.OneToOneField(UserBankAccount, on_delete=models.CASCADE, related_name="transfer_account", verbose_name="Money Recipient")
    transferDate = models.DateField(verbose_name="Date of Funds Transfer", auto_now=True)
    transferDescription = models.CharField(max_length=200, verbose_name="Funds Transfer Description", choices=TRANSFER_CHOICES, default='Funds Transfer')

    def __str__(self):
        return str(self.transferID)

bankingapp/forms.py
from django import forms
from bankingapp.models import FundsTransfer, UtilityPayment

class LoginForm(forms.Form):
    username = forms.CharField(max_length=60)
    password = forms.CharField(widget=forms.PasswordInput)


class FundsTransferForm(forms.ModelForm):
    #transferdesc = forms.CharField(max_length=200, help_text="Select Transaction Description")
    #transferaccount = forms.CharField(max_length=10, help_text="Enter Account Number")
    #transferamount = forms.IntegerField(help_text="Enter amount to transfer")
    #recipient_first_name = forms.CharField(max_length=100, help_text="Enter Recipient First Name")
    #recipient_sec_name = forms.CharField(max_length=100, help_text="Enter Recipient Second Name")
    recipient_first_name = forms.ModelChoiceField(queryset=None, empty_label="Enter recipient first name")
    recipient_sec_name = forms.ModelChoiceField(queryset=None, empty_label="Enter recipient second name")
    transferaccount = forms.ModelChoiceField(queryset=None, empty_label="Enter transfer account")


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['recipient_first_name'].queryset=FundsTransfer.objects.filter(transferAccount__accountID__first_name="")
        self.fields['recipient_sec_name'].queryset=FundsTransfer.objects.filter(transferAccount__accountID__last_name="")
        self.fields['transferaccount'].queryset=FundsTransfer.objects.filter(transferAccount__accountNumber="")


    # Providing an association between the model form and a model

    class Meta:
        model = FundsTransfer
        fields = ('transferAmount', 'transferDescription')

bankingapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from bankingapp.models import UtilityPayment, FundsTransfer, UserProfile, UserBankAccount
from django.contrib.auth import authenticate, login
from bankingapp.forms import LoginForm, FundsTransferForm
from django.contrib.auth.decorators import login_required


#paginator combiner imports
from itertools import chain

def getuser(request):
    loggeduser = None
    userid = None
    isadmin = None
    if request.user.is_authenticated():
        loggeduser = request.user.username
        userid = request.user.id
        isadmin = request.user.is_superuser
    return loggeduser, userid, isadmin

def index(request):

    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cleanedform = form.cleaned_data
            user = authenticate(username=cleanedform['username'], password=cleanedform['password'])

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return render(request, 'bankingapp/home.html', context = context_dict )
                else:
                    return HttpResponse('Disabled Account')
            else:
                return HttpResponse('Invalid Login')
    else:
        form = LoginForm()
    context_dict = { 'form': form}

    return render(request, 'bankingapp/index.html', context=context_dict)


@login_required
def apphome(request):
    loggeduser, userid, isadmin = getuser(request)

    userpersonaldetails = UserProfile.objects.filter(id=userid)
    useraccountdetails = UserBankAccount.objects.filter(accountID=userid)

    context_dict = {'loggeduser': loggeduser, 'userpersonaldetails':userpersonaldetails, 'useraccountdetails': useraccountdetails }


    return render(request, 'bankingapp/home.html', context = context_dict )

@login_required
def fundstransactions(request):
    loggeduser, userid, isadmin = getuser(request)
    if isadmin:
        fundstransfers = FundsTransfer.objects.all()
        fundstransferpaginator = Paginator(fundstransfers, 10) # List up to 10 fundstransfer transactions
        page = request.GET.get('page')

        try:
            transfers = fundstransferpaginator.page(page)
        except PageNotAnInteger:
            transfers = fundstransferpaginator.page(1)
        except EmptyPage:
            transfers = fundstransferpaginator.page(paginator.num_pages)
    else:

        fundstransfers = FundsTransfer.objects.filter(transferID_id=userid)
        fundstransferpaginator = Paginator(fundstransfers, 10) # List up to 10 fundstransfer transactions
        page = request.GET.get('page')

        try:
            transfers = fundstransferpaginator.page(page)
        except PageNotAnInteger:
            transfers = fundstransferpaginator.page(1)
        except EmptyPage:
            transfers = fundstransferpaginator.page(paginator.num_pages)

    context_dict = {'loggeduser':loggeduser, 'transfers':transfers, 'page':page }

    return render(request, 'bankingapp/fundstransactions.html', context= context_dict)

@login_required
def utilitybillstransactions(request):
    loggeduser,userid, isadmin = getuser(request)
    if isadmin:
        utilitybills = UtilityPayment.objects.all()
        billspaginator = Paginator(utilitybills, 10)
        page = request.GET.get('page')
        try:
            bills = billspaginator.page(page)
        except PageNotAnInteger:
            # if page is not an integer deliver the first page
            bills = billspaginator.page(1)
        except EmptyPage:
            # if page is out of range deliver last page of the results
            bills = billspaginator.page(paginator.num_pages)
    else:

        utilitybills = UtilityPayment.objects.filter(customerName_id=userid)
        billspaginator = Paginator(utilitybills, 10) # List 10 utility bills per page
        page = request.GET.get('page')
        try:
            bills = billspaginator.page(page)
        except PageNotAnInteger:
            # if page is not an integer deliver the first page
            bills = billspaginator.page(1)
        except EmptyPage:
            # if page is out of range deliver last page of the results
            bills = billspaginator.page(paginator.num_pages)
    context_dict = {'loggeduser': loggeduser, 'bills':bills, 'page':page}

    return render(request, 'bankingapp/utilitybillstransactions.html', context=context_dict)

@login_required
def monthlystatements(request):
    loggeduser, userid, isadmin = getuser(request)
    if isadmin:
        #if logged in user is admin, do not access commit transaction or account balance page

        context_dict = {'loggeduser':loggeduser, 'firstname': request.user.first_name, 'lastname': request.user.last_name}

        return render(request, 'bankingapp/admininfo.html', context=context_dict)
    else:
        bankaccountdetails = UserBankAccount.objects.filter(accountID=userid)
        context_dict = {'loggeduser': loggeduser, 'bankaccountdetails':bankaccountdetails }

        return render(request, 'bankingapp/monthlystatements.html', context=context_dict)


@login_required
def fundstransfer(request):
    loggeduser, userid, isadmin = getuser(request)
    if isadmin:
        context_dict = {'loggeduser':loggeduser, 'firstname': request.user.first_name, 'lastname': request.user.last_name}
        return render(request, 'bankingapp/admininfo.html', context=context_dict)
    else:
        form = FundsTransferForm()
        # A HTTP POST?
        if request.method == 'POST':
            form = FundsTransferForm(request.POST)
            # check for valid form inputs
            if form.is_valid():
                form.save(commit=True)
                return fundstransfer(request)
            else:
                print(form.errors)
        context_dict = {'loggeduser': loggeduser , 'form': form }


        return render(request, 'bankingapp/fundstransfer.html', context=context_dict)


@login_required
def payutilities(request):
    loggeduser,userid, isadmin = getuser(request)
    if isadmin:
        context_dict = {'loggeduser':loggeduser, 'firstname': request.user.first_name, 'lastname': request.user.last_name}
        return render(request, 'bankingapp/admininfo.html', context=context_dict)
    else:

        context_dict = {'loggeduser':loggeduser}

        return render(request, 'bankingapp/payutilities.html', context = context_dict)

@login_required
def updateprofile(request):
    loggeduser, userid, isadmin = getuser(request)

    if isadmin:
        context_dict = {'loggeduser': loggeduser }
        return render(request, 'bankingapp/adminupdateprofile.html', context = context_dict)
    else:
        context_dict = {'loggeduser': loggeduser }
        return render(request, 'bankingapp/updateprofile.html', context = context_dict)

@login_required
def accesslogs(request):
    loggeduser, userid, isadmin = getuser(request)
    if isadmin:

        fundstransfers = FundsTransfer.objects.all()
        utilitybills = UtilityPayment.objects.all()
        # combine fundstransfers and utilitybills querysets into a single list for pagination
        combinedlogs = list(chain(fundstransfers, utilitybills))
        combinedlogspaginator = Paginator(combinedlogs, 10)

        page = request.GET.get('page')
        try:
            logs = combinedlogspaginator.page(page)
        except PageNotAnInteger:
            # if page is not an integer deliver the first page
            logs = combinedlogspaginator.page(1)
        except EmptyPage:
            # if page is out of range deliver last page of the results
            logs = combinedlogspaginator.page(paginator.num_pages)

    else:
        fundstransfers = FundsTransfer.objects.filter(transferID=userid)
        utilitybills = UtilityPayment.objects.filter(customerName=userid)
        combinedlogs = list(chain(fundstransfers, utilitybills))
        combinedlogspaginator = Paginator(combinedlogs, 10)

        page = request.GET.get('page')
        try:
            logs = combinedlogspaginator.page(page)
        except PageNotAnInteger:
            # if page is not an integer deliver the first page
            logs = combinedlogspaginator.page(1)
        except EmptyPage:
            # if page is out of range deliver last page of the results
            logs = combinedlogspaginator.page(paginator.num_pages)



    context_dict = {'loggeduser':loggeduser,  'transfers':fundstransfers, 'billpayments':utilitybills, 'logs':logs, 'page':page }

    return render(request, 'bankingapp/accesslogs.html', context = context_dict)

def signup(request):

    context_dict = { }

    return render(request, 'bankingapp/signup.html', context = context_dict)

templates/bankingapp/accesslogs.html
{% extends 'bankingapp/baseloggedin.html'%}

{% block bodycontent %}

<div class="row">
  <div class="col-lg-12">
<h2> Your Account Access Logs </h2>
<table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Date</th>

        <th scope="col">Transaction Description</th>

      </tr>
    </thead>
    <tbody>
      {%for transfer in transfers %}
      <tr class="table-active">
        <td scope="row">{{ transfer.transferDate }}</th>

        <td>Funds Transfer to {{ transfer.transferAccount.accountID.last_name }} - Account Number {{ transfer.transferAccount.accountNumber }} </td>

      </tr>

      {% endfor %}

      {% for billpayment in billpayments %}
      <tr class="table-active">
        <td scope="row">{{ billpayment.paymentDate }}</th>

        <td>{{billpayment.billDescription }} paid to {{ billpayment.billID.companyName }} Account Number {{ billpayment.billID.companyAccountNum }} </td>

      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
</div>

{% endblock %}
{% block blockpaginator %}
{% include "bankingapp/pagination.html" with page=logs %}

{% endblock %}

templates/bankingapp/admininfo.html
{% extends 'bankingapp/baseloggedin.html' %}

{% block bodycontent %}
<div class="row">

</div>
<div class="row">
  <div class="col-lg-12">
<h2> Admin details </h2>
<table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Admin Username</th>
        <th scope="col">Admin First Name</th>

        <th scope="col">Admin Last Name</th>

      </tr>
    </thead>
    <tbody>
      <tr class="table-active">
        <td scope="row">{{ loggeduser }}</th>
        <td> {{ firstname }} </td>
        <td> {{ lastname }}</td>


      </tr>
    </tbody>
  </table>
</div>
</div>


{% endblock %}

templates/bankingapp/base.html
<!DOCTYPE html>

{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>{% block title %} Online Banking App {% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" media="screen">

    <link rel="stylesheet" href="{% static 'css/custom.min.css' %}">

  </head>
  <body>
    {% block navbar %}
    <div class="navbar navbar-expand-lg fixed-top navbar-dark bg-primary">
      <div class="container">
        <a href="{% url 'bankingapp:index' %}" class="navbar-brand">Online Banking</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav">

          </ul>

          <ul class="nav navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="#" target="_blank"></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#" target="_blank"></a>
            </li>
          </ul>

        </div>
      </div>
    </div>
    {% endblock %}


    {% block bodycontent %}

    {% endblock %}

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/banking-app-jquery.js' %}"></script>

  </body>
  </html>

templates/bankingapp/baseforforms.html
<!-- These loads bootstrap form formatting options using django-widget-tweaks -->
{% load widget_tweaks %}

  {% for hidden_field in form.hidden_fields %}
    {{ hidden_field }}

  {% endfor %}
  {% if form.non_field_errors %}
  <div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}

    {{ error }}
    {% endfor %}
  </div>
  {% endif %}

  {% for field in form.visible_fields %}

    <div class="form-group">
      {{ field.label_tag }}

      {% if form.is_bound %}

          {% if field.errors %}

              {% render_field field class="form-control is-invalid" %}

              {% for error in field.errors %}

              <div class="invalid-feedback">
                {{ error }}
          </div>
              {% endfor %}

          {% else %}

          {% render_field field class="form-control is-valid" %}

          {% endif %}

         {% else %}

        {% render_field field class="form-control" %}

      {% endif %}

      {% if field.help_text %}
        <small class="form-text" text-muted> {{ field.help_text }} </small>
      {% endif %}

    </div>

    {% endfor %}

templates/bankingapp/baseloggedin.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Online Banking App</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" media="screen">

    <link rel="stylesheet" href="{% static 'css/custom.min.css' %}">

  </head>
  <body>
    {% block navbar %}
    <div class="navbar navbar-expand-lg fixed-top navbar-dark bg-primary">
      <div class="container">
        <a href="{% url 'bankingapp:index' %}" class="navbar-brand">Online Banking</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav">

          </ul>

          <ul class="nav navbar-nav ml-auto">
            <li class="nav-item">
              <a class="navbar-brand" href="#" target="_self">{{ loggeduser }} </a>
            </li>
            <li class="nav-item">
              <b class="navbar-brand">|</b>
            </li>
            <li class="nav-item">
              <a class="navbar-brand" href="{% url  'auth_logout' %}?next=/accounts/login/" target="_self">Logout</a>
            </li>
          </ul>

        </div>
      </div>
    </div>
    {% endblock %}
    <div class="container">
      <div class="row">
        <div class="col-lg-4">
          {% block sidemenu %}

          <h2> Menu </h2>
          <ul class="list-group">
            <li class="list-group-item d-flex justify-content-between align-items-center">

              <a class="nav-link" href="{% url 'bankingapp:apphome' %}">  Home </a>

            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">

              <a class="nav-link" href="{% url 'bankingapp:fundstransactions' %}">  View Funds Transactions </a>

            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">

              <a class="nav-link" href="{% url 'bankingapp:utilitybillstransactions' %}">  View Utility Bills Transactions </a>

            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">

              <a class="nav-link" href="{% url 'bankingapp:monthlystatements' %}">  View Current Balance </a>

            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">

              <a class="nav-link" href="{% url 'bankingapp:fundstransfer' %}">  Funds Transfer  </a>

            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">

              <a class="nav-link" href="{% url 'bankingapp:payutilities' %}">  Pay Utility Bills </a>

            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">

              <a class="nav-link" href="{% url 'bankingapp:updateprofile' %}"> Update Profile </a>

            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">

              <a class="nav-link" href="{% url 'bankingapp:accesslogs' %}">  View Access Logs </a>
              <span class="badge badge-primary badge-pill">1</span>
            </li>

          </ul>

          {% endblock %}

      </div>


        <div class="col-lg-8">
          {% block bodycontent %}

          {% endblock %}

          {% block blockpaginator %}

          {% endblock %}

        </div>
      </div>
    </div>

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/banking-app-jquery.js' %}"></script>



  </body>
  </html>

templates/bankingapp/fundstransfer.html
{% extends 'bankingapp/baseloggedin.html'%}

{% block bodycontent %}
<div class="row">
  <div class="col-lg-12">
    <div class="alert alert-dismissible alert-success">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <strong>Funds have been transferred successfully! </strong>
</div>
  </div>
</div>
<div class="row">
  <div class="col-lg-12">
    <form id="funds_transfer" method="post" action="/bankingapp/fundstransfer">
      {%csrf_token %}
      
      {% include 'bankingapp/baseforforms.html' with form=form %}

    </form>
    <form>
  <fieldset>
    <div class="form-group">
      <label class="col-form-label" for="transactionType"> Transaction description </label>
    <select class="custom-select">
      <option value="1">Funds Transfer</option>
      </select>
  </div>
    <div class="form-group">
      <label class="col-form-label" for="reciepientAccountNum">Recipient Account Number</label>
      <input class="form-control" placeholder="Enter Account # of the Recipient" id="reciepientAccountNum" name="reciepientAccNum" type="text">
    </div>
    <div class="form-group">
      <label class="col-form-label" for="reciepientFirstName">Recipient First Name</label>
      <input class="form-control" placeholder="Enter Recipient 1st Name" id="reciepientFirstName"  name="reciepientFName" type="text">
    </div>
    <div class="form-group">
      <label class="col-form-label" for="reciepientSecondName">Recipient Second Name</label>
      <input class="form-control" placeholder="Enter Recipient Second Name" id="reciepientSecondName" name="reciepientSecName" type="text">
    </div>
    <div class="form-group">
      <label class="col-form-label" for="transferAmount">Transfer Amount</label>
      <input class="form-control" placeholder="Enter Amount to Transfer" id="transferAmount" name="transAmount" type="text">
    </div>


    <button type="submit" class="btn btn-primary">Send Money</button>
  </fieldset>
</form>

  </div>
</div>

{% endblock %}

templates/bankingapp/pagination.html
<div>
  <ul class="pagination pagination-lg">
    {% if page.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page.previous_page_number }}"> Previous </a>
      </li>
      {% endif %}
      <li class="page-item active">
        <a class="page-link" href="#"> {{ page.number }} of {{ page.paginator.num_pages }}</a>
      </li>


        <li class="page-item">
            {% if page.has_next %}
        <a class="page-link" href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
      </li>
    </ul>
  </div>

templates/bankingapp/signup.html
{% extends 'bankingapp/base.html' %}

{% block bodycontent %}
<div class="container">

     <div class="row">
       <div class="col-lg-5">
         <div class="jumbotron">
          <h1 class="display-4">XYZ Online Banking App</h1>

          <hr class="my-4">
          <p>Login to XYZ online banking platform</p>
          <p class="lead">
            <a class="btn btn-primary btn-lg" href="{% url 'bankingapp:index' %}" role="button">Already Signed Up? Login</a>
          </p>
        </div>
       </div>
       <div class="col-lg-7">
         <form>
           <fieldset>


               <h1> Sign Up </h1>
               <div class="form-group">
                 <label for="firstname">First Name</label>
                 <input type="text" class="form-control" id="firstname" aria-describedby="firstname" placeholder="Enter your first name">

               </div>
               <div class="form-group">
                 <label for="secondname">Second Name</label>
                 <input type="text" class="form-control" id="secondname" aria-describedby="secondname" placeholder="Enter your second name">

               </div>

             <div class="form-group">
               <label for="username">Username</label>
               <input type="text" class="form-control" id="username" aria-describedby="username" placeholder="Enter your preferred username">

             </div>
             <div class="form-group">
               <label for="email">Username</label>
               <input type="text" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Enter your email">

             </div>
             <div class="form-group">
               <label for="password">Password</label>
               <input type="password" class="form-control" id="password" placeholder="Enter your password">
             </div>
             <div class="form-group">
               <label for="password2">Password</label>
               <input type="password" class="form-control" id="password2" placeholder="Enter your password again">
             </div>

             <button type="submit" class="btn btn-primary btn-lg">  Sign Up  </button>
           </fieldset>
         </form>

       </div>
     </div>

{% endblock %}